# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60844f4bc322ac685e3e003dbee460c0bd988ad0458bce13d57112f46cdfe21add0d60174ebd2295a11eae4bbb8432a3b83c72463e5aff02696ee089cc83f756

test:
  secret_key_base: 82984299b48660502dc43b1eda2f82bc7069ab3014bbbf443c74073d4c4eac9a7e5926bfcdf071a41106f27d80cbe4dd001cc5e5bbcbcf31ae6035df4e9dbd96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
